project_id = "fipebdkvzdrljwwxccrj"

[functions.send-email]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.create-stripe-checkout]
verify_jwt = false

[functions.verify-stripe-payment]
verify_jwt = false

[functions.check-ai-tokens]
verify_jwt = false

[functions.increment-ai-tokens]
verify_jwt = false

[functions.generate-ai-token]
verify_jwt = false

[functions.runware-image-edit]
verify_jwt = true

[functions.runware-video-generation]
verify_jwt = true