project_id = "fipebdkvzdrljwwxccrj"

[auth]
enable_signup = true
enable_confirmations = true

[auth.external]

[auth.email]
enable_signup = true
enable_confirmations = true

[auth.email.template.confirmation]
subject = "Welcome to Exhibit3Design - Confirm Your Account"

[auth.hook.send_email]
enabled = true
uri = "https://fipebdkvzdrljwwxccrj.supabase.co/functions/v1/send-confirmation-email"

[functions.send-confirmation-email]
verify_jwt = false