project_id = "fipebdkvzdrljwwxccrj"

[functions.send-email]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.create-stripe-checkout]
verify_jwt = false

[functions.verify-stripe-payment]
verify_jwt = false