project_id = "fipebdkvzdrljwwxccrj"

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false